server:
  port: 9000

security:
  jwt:
    key-store: classpath:cyborg.jks
    key-store-password: 123456
    key-pair-alias: cyborg
    key-pair-password: 123456

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    show-sql: true
  database:
    datasource:
      driverClassName: org.h2.Driver
      jdbcUrl: jdbc:h2:mem:testdb
      username: sa
      password: