spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
